# WINDOW
WINDOW_SIZE = WINDOW_X, WINDOW_Y = 800, 600

# TILE
TILE_SIZE = TILE_X, TILE_Y = 50, 50

# PLAYER
PLAYER_SIZE = PLAYER_X, PLAYER_Y = 15, 15

PLAYER_SPEED = 0.2

PLAYER_LOCK_X_MIN = 150
PLAYER_LOCK_X_MAX = 650
PLAYER_LOCK_Y_MIN = 130
PLAYER_LOCK_Y_MAX = 470

# LEVEL
LEVEL_FILE_PATH = "data/levels"

