# WINDOW
WINDOW_SIZE = WINDOW_X, WINDOW_Y = 800, 600

# TILE
TILE_SIZE = TILE_X, TILE_Y = 50, 50

# PLAYER
PLAYER_SIZE = PLAYER_X, PLAYER_Y = 40, 40

PLAYER_SPEED = 0.2

PLAYER_LOCK_X_MIN = WINDOW_X // 2
PLAYER_LOCK_X_MAX = WINDOW_X - PLAYER_LOCK_X_MIN
PLAYER_LOCK_Y_MIN = WINDOW_Y // 2
PLAYER_LOCK_Y_MAX = WINDOW_Y - PLAYER_LOCK_Y_MIN

# LEVEL
LEVEL_PATH = "data/levels/{level_id}/{level_id}_{layer_type}.csv"
ASSETS_PATH = "assets/"

# DEBUG
DEBUG = True
